name: heart-failure-prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=21.0
  - scikit-learn>=1.2.0
  - pandas>=2.0.0
  - numpy>=1.24.0
  - matplotlib>=3.5.0
  - seaborn>=0.12.0
  - pip:
    - mlflow>=2.19.0
    - joblib>=1.1.0
    - dagshub>=0.3.0
