name: Heart Failure Model CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      run_name:
        description: 'MLflow run name'
        required: true
        default: 'CI-Triggered-Run'

jobs:
  train_model:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install MLflow
      run: pip install mlflow
      
    - name: Train model with MLflow Project
      run: |
        cd ${{ github.workspace }}
        mlflow run MLProject \
          --no-conda \
          --run-id ${{ github.run_id }} \
          -P run_name="${{ github.event.inputs.run_name || 'github-actions-run' }}"
          
    - name: Upload MLflow artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: MLProject/mlruns
